name: Build and Deploy to App Service

on:
  push:
    branches:
      - main

env:
  AZURE_APP_SERVICE_NAME: 'micro-frontend-container'

concurrency:
  group: deploy-develop
  cancel-in-progress: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Azure CLI
        run: sh ./.github/scripts/install-azure-cli.sh

      - name: Log into Azure CLI with service principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.WEB_APP_SP }}

      - name: Log into Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: shubhamdregistry.azurecr.io
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: docker build .
          --file infra/Dockerfile
          --build-arg GIT_SHA=${{ github.sha }}
          --tag shubhamdregistry.azurecr.io/micro-frontend-container:develop

      - name: Push to Azure Container Registry
        run: docker push shubhamdregistry.azurecr.io/micro-frontend-container:develop

      - name: Deploy App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_APP_SERVICE_NAME }}