name: deploy-container-manual

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

env:
  MARKETING_URL: ${{ secrets.MARKETING_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Logging
        run: |
          echo "${{toJSON(github.event.commits)}}"
      - id: getjiraticket
        run: echo "::set-output name=jiraticketid::`echo "${{ github.event.commits[0].message }}" | sed -nE 's,[a-z]+/([A-Z]+-[0-9]+)-.+,\1,p'`"
      - name: Print Jira Tikcet number
        run: echo ${{ steps.getjiraticket.outputs.jiraticketid }}
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          git config --global user.name shubhamdeodia
          git config --global user.email shubh.deodia@gmail.com
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
